# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.2"

  config.vm.provision "shell", path: "bootstrap.sh" 
 
  # Loop three times
  (1..3).each do |i|
    # Defining VM properties 
    config.vm.define "node#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.33.2#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.name = "rabbitmq-node-#{i}"
      end
      node.vm.hostname = "node#{i}"
      node.vm.network "forwarded_port", guest: 5672,   host: "#{i}5672"  #Node port
      node.vm.network "forwarded_port", guest: 15672,  host: "#{i}5673" #Management port
    
      #Runs: puppet apply --verbose /vagrant/manifests/default.pp
      node.vm.provision "puppet" do |puppet| 
        puppet.options = "--verbose"
      end
    end
  end
end
