# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.provision "shell", path: "bootstrap.sh"   

    
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose"
  end
 
  config.vm.network "private_network", ip: "192.168.33.101"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.name = "keeper"
  end
  config.vm.hostname = "keeper"
    

end
