# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.network "forwarded_port", guest: 5050,  host: 5050

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.name = "mesos-test"
  end
  
  config.vm.hostname = "mesos-test"
  config.vm.provision "shell", path: "bootstrap.sh" 
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose"
  end
end
