# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.2"
  
  config.vm.network "forwarded_port", guest: 5672,   host: 5672  #Node port
  config.vm.network "forwarded_port", guest: 15672,  host: 15672 #Management port

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.name = "rabbitmq-test"
  end
  
  config.vm.hostname = "guest"
  config.vm.provision "shell", path: "bootstrap.sh" 
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose"
  end
end
