# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.7"

  config.vm.provision "shell", path: "bootstrap.sh"   

  config.vm.define "master1" do |master1|
  
    master1.vm.network "forwarded_port", guest: 50070,  host: 50070
    master1.vm.network "forwarded_port", guest: 8088, guest_ip: "192.168.33.11", host: 8088
    
    master1.vm.network "private_network", ip: "192.168.33.11"
    master1.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.name = "hadoop-master-1"
    end
    master1.vm.hostname = "master1"
    
    master1.vm.provision "puppet" do |puppet|
      puppet.options = "--verbose"
    end
  end
 
  # Loop three times
  (1..3).each do |i|
    # Defining VM properties 
    config.vm.define "slave#{i}" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.2#{i}"
      slave.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.name = "hadoop-slave-#{i}"
      end
      slave.vm.hostname = "slave#{i}"
    
      slave.vm.provision "puppet" do |puppet|
        puppet.options = "--verbose"
      end
    end
  end

end
